.latexEscape <- function(x) {
  x <- gsub("\\\\", "\\\\textbackslash{}", x, fixed = TRUE)
  x <- gsub("_", "\\\\_", x, fixed = TRUE)
  x <- gsub("%", "\\\\%", x, fixed = TRUE)
  x <- gsub("&", "\\\\&", x, fixed = TRUE)
  x <- gsub("#", "\\\\#", x, fixed = TRUE)
  x
}

#' Resolve SS3 base path and run table from a study spec or explicit base
#'
#' Uses \code{diags::loadStudySpec()} when \code{studyId} is given. Override base
#' with \code{base} or \code{DIAG_SS_BASE}.
#'
#' @param base Assessment parent directory.
#' @param studyId Study bundle id (\code{studies/<id>.R}).
#' @param appendixDir Appendices root containing \code{studies/}.
#' @param register Optional scenario register (defaults from study spec).
#' @param discover Scan \code{base} for all \code{Report.sso} runs.
#' @param includeSensitivity Include sensitivity ids from register when not discovering.
#' @export
ssStudyRuns <- function(
  base = NULL,
  studyId = NULL,
  appendixDir = NULL,
  register = NULL,
  discover = NULL,
  includeSensitivity = FALSE
) {
  spec <- NULL
  if (!is.null(studyId) && nzchar(studyId)) {
    if (is.null(appendixDir)) {
      appendixDir <- normalizePath("appendices", winslash = "/", mustWork = FALSE)
      if (!dir.exists(appendixDir)) {
        stop(
          "Provide appendixDir or setwd() to a project with appendices/.",
          call. = FALSE
        )
      }
    }
    spec <- diags::loadStudySpec(studyId, appendixDir)
    register <- register %||% spec$scenarios
  }

  ssBase <- base
  if (is.null(ssBase) || !nzchar(ssBase)) {
    ssBase <- Sys.getenv("DIAG_SS_BASE", unset = "")
  }
  if ((!nzchar(ssBase) || is.null(ssBase)) && !is.null(spec)) {
    cfg <- diags::studySpecToConfig(spec, appendixDir)
    ssBase <- cfg$assessment_base
  }
  if (is.null(ssBase) || !nzchar(ssBase)) {
    stop("Provide base, DIAG_SS_BASE, or studyId with paths in spec.", call. = FALSE)
  }
  ssBase <- normalizePath(ssBase, winslash = "/", mustWork = FALSE)

  if (is.null(discover)) {
    discover <- isTRUE(includeSensitivity)
  }

  scenarios <- if (!is.null(spec)) {
    as.character(spec$scenarios$ids)
  } else {
    character(0)
  }
  runs <- NULL

  if (isTRUE(discover)) {
    runs <- ssRuns(ssBase)
    scenarios <- runs$id
    if (!length(scenarios)) {
      stop("No Report.sso runs found under ", ssBase, call. = FALSE)
    }
    message("[ssStudyRuns] discovered ", length(scenarios), " runs under ", ssBase)
  } else if (isTRUE(includeSensitivity) && !is.null(register)) {
    sens <- register$sensitivity_register
    if (is.data.frame(sens) && "id" %in% names(sens)) {
      scenarios <- unique(c(scenarios, as.character(sens$id)))
    }
    runs <- ssRuns(ssBase, scenarios)
  }

  if (is.null(runs) || !NROW(runs)) {
    if (!length(scenarios) && !is.null(register) && !is.null(register$ids)) {
      scenarios <- as.character(register$ids)
    }
    runs <- ssRuns(ssBase, scenarios)
  }

  list(
    base = ssBase,
    scenarios = scenarios,
    runs = runs,
    register = register,
    spec = spec,
    studyId = studyId
  )
}

#' Write scenario catalog to CSV and RDS
#' @param catalog \code{ssCatalog()} data frame.
#' @param outDir Output directory.
#' @return Named character vector of output paths.
#' @export
ssSaveCatalog <- function(catalog, outDir) {
  dir.create(outDir, recursive = TRUE, showWarnings = FALSE)
  csv <- file.path(outDir, "scenario-catalog.csv")
  rds <- file.path(outDir, "scenario-catalog.rds")
  utils::write.csv(catalog, csv, row.names = FALSE)
  saveRDS(catalog, rds)
  c(csv = csv, rds = rds)
}

#' Write LaTeX table from scenario catalog
#' @param catalog \code{ssCatalog()} data frame.
#' @param path Output \code{.tex} file.
#' @param caption,label Table caption and label.
#' @export
ssCatalogTex <- function(
  catalog,
  path,
  caption = "SS3 base and sensitivity runs with standardized ids.",
  label = "tab:scenario-catalog"
) {
  roleLab <- c(base = "Base", sensitivity = "Sens", other = "Other")
  lines <- c(
    "% Auto-generated by sstruth::ssCatalogTex()",
    "",
    "\\begin{table}[H]",
    "\\centering",
    "\\small",
    sprintf("\\caption{%s}", .latexEscape(caption)),
    sprintf("\\label{%s}", label),
    "\\begin{tabular}{llllp{5.5cm}}",
    "\\toprule",
    "Scenario & Role & Std id & Run directory & Description \\\\",
    "\\midrule"
  )
  ord <- order(catalog$scenario, catalog$role, catalog$stdId)
  catDF <- catalog[ord, , drop = FALSE]
  for (i in seq_len(nrow(catDF))) {
    row <- catDF[i, , drop = FALSE]
    desc <- row$label[[1L]]
    if (!is.na(row$purpose[[1L]]) && nzchar(row$purpose[[1L]])) {
      desc <- paste(desc, row$purpose[[1L]], sep = ": ")
    }
    lines <- c(
      lines,
      paste0(
        .latexEscape(row$scenario[[1L]]), " & ",
        roleLab[[row$role[[1L]]]] %||% row$role[[1L]], " & ",
        "\\texttt{", .latexEscape(row$stdId[[1L]]), "} & ",
        "\\texttt{", .latexEscape(row$id[[1L]]), "} & ",
        .latexEscape(desc), " \\\\"
      )
    )
  }
  lines <- c(lines, "\\bottomrule", "\\end{tabular}", "\\end{table}", "")
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, path, useBytes = TRUE)
  invisible(path)
}

#' Three-step scenario setup under an assessment folder
#'
#' \enumerate{
#'   \item List nested scenarios (\code{ssRuns()} + \code{ssCatalog()}).
#'   \item Cache \code{SS_output} in each run folder (\code{SS_outputs()}).
#'   \item Cache \code{FLStock} in each run folder (\code{readFLSss3()}).
#' }
#'
#' @param base Assessment parent (or from study spec / \code{DIAG_SS_BASE}).
#' @param studyId,appendixDir Study bundle location.
#' @param register Scenario register list or \code{study_spec()$scenarios}.
#' @param discover Scan \code{base} for all \code{Report.sso} runs.
#' @param listRuns Step i — discover runs and write catalog (+ LaTeX).
#' @param ssOutput Step ii — \code{SS_outputs()} into each run folder.
#' @param flStock Step iii — \code{readFLSss3()} into each run folder.
#' @param artifacts If \code{TRUE}, also run \code{ssExportRuns()} (CPUE/lencomp inputs/fits).
#' @param listOnly Step i only (\code{listRuns} without ii/iii).
#' @param outDir Catalog CSV/RDS directory.
#' @param texOut LaTeX table path.
#' @param refresh,parallel,workers Passed to \code{SS_outputs()} / \code{readFLSss3()}.
#' @return List with \code{runs}, \code{catalog}, \code{ssOutput} and \code{flStock}
#'   status data frames (not the cached objects themselves).
#' @inheritParams ssCatalogTex
#' @export
ssScenarios <- function(
  base = NULL,
  studyId = NULL,
  appendixDir = NULL,
  register = NULL,
  discover = TRUE,
  listRuns = TRUE,
  ssOutput = NULL,
  flStock = NULL,
  artifacts = FALSE,
  listOnly = FALSE,
  outDir = NULL,
  texOut = NULL,
  refresh = FALSE,
  parallel = TRUE,
  workers = NULL,
  caption = NULL,
  label = "tab:scenario-catalog"
) {
  if (isTRUE(listOnly)) {
    ssOutput <- FALSE
    flStock <- FALSE
    listRuns <- TRUE
  } else if (is.null(ssOutput) && is.null(flStock)) {
    ssOutput <- TRUE
    flStock <- TRUE
  } else {
    if (is.null(ssOutput)) ssOutput <- FALSE
    if (is.null(flStock)) flStock <- FALSE
  }

  ctx <- ssStudyRuns(
    base = base,
    studyId = studyId,
    appendixDir = appendixDir,
    register = register,
    discover = discover,
    includeSensitivity = discover
  )
  register <- ctx$register

  catalog <- NULL
  paths <- NULL
  texPath <- NULL

  if (isTRUE(listRuns)) {
    catalog <- ssCatalog(base = ctx$base, runs = ctx$runs, register = register)
    message(
      "[ssScenarios] i) ", nrow(catalog), " runs (",
      sum(catalog$role == "base"), " base, ",
      sum(catalog$role == "sensitivity"), " sens)"
    )

    sid <- studyId %||% ctx$spec$study_id %||% "ss3"
    if (is.null(outDir) || !nzchar(outDir)) {
      ad <- appendixDir
      if (is.null(ad) || !nzchar(ad)) {
        ad <- normalizePath("appendices", winslash = "/", mustWork = FALSE)
      }
      outDir <- file.path(ad, "data", sid)
    }
    paths <- ssSaveCatalog(catalog, outDir)
    message("[ssScenarios] catalog -> ", paths[["csv"]])

    if (is.null(texOut) || !nzchar(texOut)) {
      ad <- appendixDir
      if (is.null(ad) || !nzchar(ad)) {
        ad <- normalizePath("appendices", winslash = "/", mustWork = FALSE)
      }
      texOut <- file.path(ad, "content", "sma", "scenario-catalog.tex")
    }
    ssCatalogTex(catalog, texOut, caption = caption %||% {
      "SS3 base and sensitivity runs with standardized ids."
    }, label = label)
    texPath <- texOut
    message("[ssScenarios] LaTeX -> ", texPath)
  }

  ssOutStatus <- NULL
  flStockStatus <- NULL
  artifactStatus <- NULL

  if (isTRUE(ssOutput)) {
    message("[ssScenarios] ii) SS_outputs()")
    ssOutStatus <- SS_outputs(
      ctx$runs,
      refresh = refresh,
      parallel = parallel,
      workers = workers
    )
  }

  if (isTRUE(flStock)) {
    message("[ssScenarios] iii) readFLSss3()")
    flStockStatus <- readFLSss3(
      ctx$runs,
      writeCache = TRUE,
      returnObjects = FALSE,
      parallel = parallel,
      workers = workers
    )
  }

  if (isTRUE(artifacts)) {
    if (is.null(catalog)) {
      catalog <- ssCatalog(base = ctx$base, runs = ctx$runs, register = register)
    }
    artifactStatus <- ssExportRuns(
      ctx$runs,
      catalog = catalog,
      register = register,
      refresh = refresh,
      flr = FALSE,
      parallel = parallel,
      workers = workers
    )
    if (!is.null(outDir) && nzchar(outDir)) {
      exportPath <- file.path(outDir, "scenario-export-status.csv")
      utils::write.csv(artifactStatus, exportPath, row.names = FALSE)
      message("[ssScenarios] artifacts -> ", exportPath)
    }
  }

  structure(
    list(
      runs = ctx$runs,
      base = ctx$base,
      register = register,
      catalog = catalog,
      paths = paths,
      tex = texPath,
      ssOutput = ssOutStatus,
      flStock = flStockStatus,
      artifacts = artifactStatus
    ),
    class = "ssScenarios"
  )
}

.parseScenariosArgs <- function(args) {
  out <- list(
    appendixDir = NULL,
    studyId = Sys.getenv("DIAG_STUDY", unset = "sma-2026"),
    base = NULL,
    listOnly = FALSE,
    ssOutput = FALSE,
    flStock = FALSE,
    artifacts = FALSE,
    refresh = FALSE,
    parallel = TRUE,
    workers = NULL,
    outDir = NULL,
    texOut = NULL
  )
  i <- 1L
  while (i <= length(args)) {
    key <- args[[i]]
    if (key %in% c("--appendix-dir", "--study", "--ss-base", "--out-dir",
                   "--tex-out", "--workers") && i < length(args)) {
      val <- args[[i + 1L]]
      if (key == "--appendix-dir") out$appendixDir <- val
      else if (key == "--study") out$studyId <- val
      else if (key == "--ss-base") out$base <- val
      else if (key == "--out-dir") out$outDir <- val
      else if (key == "--tex-out") out$texOut <- val
      else if (key == "--workers") out$workers <- as.integer(val)
      i <- i + 2L
    } else if (key %in% c("--list-only", "--catalog-only")) {
      out$listOnly <- TRUE
      i <- i + 1L
    } else if (key %in% c("--ss-output", "--collect")) {
      out$ssOutput <- TRUE
      i <- i + 1L
    } else if (key %in% c("--flstock", "--export")) {
      out$flStock <- TRUE
      i <- i + 1L
    } else if (key == "--artifacts") {
      out$artifacts <- TRUE
      i <- i + 1L
    } else if (key == "--refresh") {
      out$refresh <- TRUE
      i <- i + 1L
    } else if (key == "--parallel") {
      out$parallel <- TRUE
      i <- i + 1L
    } else if (key == "--no-parallel") {
      out$parallel <- FALSE
      i <- i + 1L
    } else {
      i <- i + 1L
    }
  }
  out
}

#' CLI entry point for the three-step scenario workflow
#'
#' @param args Character vector of command-line arguments (default: trailing args).
#' @export
ssScenariosCli <- function(args = commandArgs(trailingOnly = TRUE)) {
  if ("--help" %in% args || "-h" %in% args) {
    cat(
      "Usage: Rscript 00_scenarios.R [options]\n\n",
      "  i)   List nested scenarios (ssRuns + catalog)\n",
      "  ii)  SS_outputs()  -> ss_output.rds in each run folder\n",
      "  iii) readFLSss3() -> flstock.rds in each run folder\n\n",
      "Options:\n",
      "  --study ID           Study bundle (default: sma-2026)\n",
      "  --appendix-dir DIR   Appendices root\n",
      "  --ss-base PATH       SS3 parent directory (or DIAG_SS_BASE)\n",
      "  --list-only          Step i only\n",
      "  --ss-output          Step ii only (with i)\n",
      "  --flstock            Step iii only (with i, ii)\n",
      "  --artifacts          Also export CPUE/lencomp inputs/fits\n",
      "  --refresh            Re-read Report.sso\n",
      "  --workers N          Parallel workers\n",
      "  --out-dir DIR        Catalog CSV/RDS\n",
      "  --tex-out FILE       LaTeX scenario table\n",
      sep = ""
    )
    return(invisible(NULL))
  }

  parsed <- .parseScenariosArgs(args)
  runAll <- !parsed$listOnly && !parsed$ssOutput && !parsed$flStock

  appendixDir <- parsed$appendixDir
  if (is.null(appendixDir) || !nzchar(appendixDir)) {
    appendixDir <- normalizePath("appendices", winslash = "/", mustWork = FALSE)
  }

  ssScenarios(
    base = parsed$base,
    studyId = parsed$studyId,
    appendixDir = appendixDir,
    discover = TRUE,
    listOnly = parsed$listOnly,
    listRuns = TRUE,
    ssOutput = parsed$ssOutput || runAll,
    flStock = parsed$flStock || runAll,
    artifacts = parsed$artifacts,
    outDir = parsed$outDir,
    texOut = parsed$texOut,
    refresh = parsed$refresh,
    parallel = parsed$parallel,
    workers = parsed$workers
  )
}
